### ISSUE TITLE
Error while trying to download Desktop Agent 3

### ISSUE THREAD

**Issue by nomssi** [SAP-samples/teched2022-AI180#1]
I cannot install the Desktop Agent 3.
I am on SAP BTP Trial Account. While trying to follow the tutorial

https://developers.sap.com/tutorials/spa-setup-desktop-3-0-agent.html
Step 2 / 2. Select Go to RBSC portal button.

always yield an -> 500 Internal Server Error

If I go to the download page directly, the error ist "Agent cannot be downloaded, contact your Admin".

Do you have any hints?

best regards,

Jacques Nomssi

**Comment by chaitanya-priya-puvvada** [comment]
Jacques Nomssi,
Can we connect to check your issue?

**Comment by nomssi** [comment]
Hello Chaitanya Priya Puvvada,

sure, we can connect. Just tell me how. 
I started following you @chaitanyapriya.puvvada on SAP Community.
If you also follow me, we can chat/set setup a session.

I could reproduce the issue today: 

When I click on the button the go to the RBSC-Portal

![image](https://user-images.githubusercontent.com/18452507/203034637-4f419a2c-47fa-47b2-a3d8-9c5e197ab1f6.png)

I get this error:

![image](https://user-images.githubusercontent.com/18452507/203034761-d2b4f01d-08ea-4a76-b050-415d2a655499.png)

best regards,

Jacques Nomssi

**Comment by nomssi** [comment]
Note I am using the Universal ID to log in. Could this be related ?

**Comment by chaitanya-priya-puvvada** [comment]
Can you share ur email ID?I can set up a call tomorrow and check your issue.

**Comment by nomssi** [comment]
It is "nomssi @ gmail . com"

**Comment by chaitanya-priya-puvvada** [comment]
I just sent a meeting request to connect and check the issue

**Comment by chaitanya-priya-puvvada** [comment]
We connected and checked your issues. We will check internally and get back to u on that.
Meantime please install Desktop Agent 2 https://developers.sap.com/tutorials/spa-setup-desktop-agent.html
